DECLARE
v_id_cliente NUMBER := 2600;
v_tipo_cliente VARCHAR2(100);


BEGIN 

SELECT CTBCDESCTIPOCLIENTE INTO v_tipo_cliente FROM CTBC_TIPO_CLIENTE 
INNER JOIN SW_CUSTOMER 
ON CTBC_TIPO_CLIENTE.CTBCTIPOCLIENTEID = SW_CUSTOMER.CTBCTIPOCLIENTEID
WHERE SW_CUSTOMER.SWCUSTOMERID = v_id_cliente;

DBMS_OUTPUT.PUT_LINE('O cliente eh: '|| v_tipo_cliente);

END;
