DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(CTBCTIPOAGREEMENTID)
  INTO v_count
  FROM SW_AGREEMENT
  WHERE CTBCTIPOAGREEMENTID = 1.0
  AND SWDATECREATED >= SYSDATE - 30;
  
  DBMS_OUTPUT.PUT_LINE('Quantidade de contratos com CTBCTIPOAGREEMENTID = 1.0 criados nos últimos 30 dias: ' || v_count);
END;
